apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stack
spec:
  selector:
    matchLabels:
      app: nginx
      version: 1.15.8
  replicas: 3
  template:
    metadata:
      labels: 
        app: nginx
        version: 1.15.8
    spec:
      containers:
      - name: nginx-1.15.8
        image: "nginx:1.15.8"
        ports:
          - containerPort: 80
