apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-replica
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        version: "2"
    spec:
      containers:
        - name: nginx-1-15-8
          image: "nginx:1.15.8"